### PR TITLE
Vendor machinehealthcheck tests

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Vendor machine health check tests from the cluster-api-actuator-pkg repository.

Relevant PR under the `cluster-api-actuator-pkg` repository - https://github.com/openshift/cluster-api-actuator-pkg/pull/47

```
47c603ff Merge pull request #49 from ingvagabund/code-improvements
e734831f Detect kubemark based on presence of machineapi-kubemark-controllers deployment
5c7fd8e9 Get the latest revision of a machine object before updating it
95fed5db Use GetMachineSet to retrieve a machineset by its name
7242ac6c Set the default machineset Replicas field in constant
9d9e98cf Move util functions under utils.go
5fb1ddfe Do not use ginkgo/gomega naturalisms outside the main execution
8de61aa1 Be more verbose when failed to delete a resources
949b9a6e Improve code readibility
3ae752aa List nodes directly without any retry logic
4e07125f Create workload directly without any retry logic
c2ef4e17 Fix error message
e0e35ef7 Create CA and MA only once without any retry logic
66f31b52 Implement and apply DeleteObjectsByLabels
e4c63b7c Dereference a pointer only once
c0123276 List machineset list directly without retry logic
ff0ceade Build CA and MA resources within a function
14df399d Get machine directly without retry logic
9bb870a9 List machines directly without retry logic
c8a30176 List machinesets directly without retry logic
f59eb63b List nodes directly without retry logic
90efba3f Remove getMachineSetList in favor of getMachineSets
5963bfe5 Refactor getClusterSize to get nodes by calling getNodes
d881f928 Remove getNodeList in favor of getNodes
00598362 Makefile: build e2e
bae7e399 Remove getMachineList in favor of getMachines
6c9c0c00 Merge pull request #47 from cynepco3hahue/machine-healthcheck-tests
d1ea8713 Introduce machinehealthcheck tests
0785ce82 Vendor machine-api-operator
b418c217 Merge pull request #48 from frobware/bump-autoscaler-workload-timeout
8e7f0509 e2e/autoscaler: Bump autoscaler workload timeout
6da15dab Merge pull request #46 from frobware/fix-autoscaler-e2e-flaky-test
d7aba749 e2e/autoscaler/autoscaler: remove ActiveDeadlineSeconds from job
56b034e0 Merge pull request #44 from enxebre/taints
52e48ab3 Update machineSetsSnapShotLogs name
47bebf0f Update taints test to use dsl
c0baabd4 Merge pull request #45 from enxebre/operators-update
8af29489 Add nodes snapshot
85de4df7 Refactor deployments for operators
38ae1c23 Merge pull request #43 from enxebre/scaling-story
311ba82a Add scaling stories
502fb706 Rephrase Describe
135224d8 Merge pull request #42 from enxebre/recover-story
bf7ebeb5 Revendor for k8s.io/utils/pointer
f96f4c4f Improve 'recover from deleted worker machines' story
ea7dd9a6 Merge pull request #41 from enxebre/linked-nodes-fix
78143390 Abstract function for 'have machines resources backing nodes' story
023f28f6 Expect same number of machines and nodes
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@ingvagabund Hi, I can see this test
```
Machine API operator deployment should
[90m/data/src/github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go:11[0m
  [91m[1mreconcile controllers deployment [It][0m
  [90m/data/src/github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/machine-api-operator.go:21[0m
```
fails consistently under the kubemark environment, can it be related to some changes under the `cluster-api-actuator-pkg` repository?

**Comment by ingvagabund** [comment]
> fails consistently under the kubemark environment, can it be related to some changes under the cluster-api-actuator-pkg repository?

It's flaking occasionally. The rest of the tests failed due to missing machineset manifests. I have update underlying Jenkins Job.

/retest

**Comment by ingvagabund** [comment]
Though, I will ask you to wait a bit and revendor again once we merge https://github.com/openshift/cluster-api-actuator-pkg/pull/49. I have found a bug in the machine healtchecking tests. If the tests are run at the beginning of the test suite, the worker nodes does not have enough time to pop up. So the tests fail. I have moved the check for kubemark provider sooner in the BeforeEach/AfterEach functions so it really skips the tests right away.

**Comment by cynepco3hahue** [comment]
@ingvagabund Sure it already no so critical:) By the way maybe it better to add `BeforeSuite` method that will wait for some specific state of the environment before start tests. What do you think?

**Comment by ingvagabund** [comment]
> that will wait for some specific state of the environment before start tests

That's one of our plans. We want to assert expected state of the cluster and wait for it for a while before a test starts running. Though, can't say when that happens.

**Comment by cynepco3hahue** [comment]
@ingvagabund Maybe I can help with this if we can describe default CI environment
Currently, I saw `kubemark` is different from `aws` by the number of nodes.

**Comment by enxebre** [comment]
can you please add a link to the relevant PR on the description a git log --oneline diff of the commits e.g https://github.com/openshift/cluster-api-provider-aws/pull/178

**Comment by cynepco3hahue** [comment]
@ingvagabund I updated the `cluster-api-actuator-pkg` package
@enxebre Updated the description

**Comment by enxebre** [comment]
@cynepco3hahue but the diff shows changes to the `/autoscaler/autoscaler.go` but I can't see anything related in the description, would you mind to include the `git log --oneline` diff of the current commit and the one being introduced by this PR e.g openshift/cluster-api-provider-aws#178

**Comment by cynepco3hahue** [comment]
@enxebre Done

**Pull request merged**
