### PR TITLE
[release-4.6] Bug 1916772: Inject the cluster-wide proxy environment variables in the baremetal pod

### PR DESCRIPTION
**Pull request by kirankt**
This PR mounts the trusted CA bundle and injects the proxy environment variables into all of the baremetal pod containers.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
This seems reasonable but you'll need to create a bug for 4.7 and send that through QE first, once they have verified there is no issue in 4.7, we will be able to merge this as well.

**Comment by kirankt** [comment]
/retitle [release-4.6] Bug 1916772: Inject the cluster-wide proxy environment variables in the baremetal pod

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Comment by ashcrow** [comment]
(patch manager) This seems to be indicating that this work is a backport of https://github.com/openshift/cluster-baremetal-operator/pull/117. However, the changes are in different components and different code. Is this accurate?

**Comment by kirankt** [comment]
> (patch manager) This seems to be indicating that this work is a backport of [openshift/cluster-baremetal-operator#117](https://github.com/openshift/cluster-baremetal-operator/pull/117). However, the changes are in different components and different code. Is this accurate?

Hello. This is correct. In the 4.6 release the relevant code existed in this repository but moved to cluster-baremetal-operator in 4.7 and later releases.  Also, FYI, the current failing test (e2e-aws-workers-rhel7) is not related to this patch and can be safely ignored. Thanks.

**Comment by kirankt** [comment]
@JoelSpeed . Hi. Do you mind overriding the e2e-aws-workers-rhel7 test, please? Its not related to this PR (which only affects our baremetal-ipi platform). Thanks.

**Comment by stbenjam** [comment]
Looks like e2e-aws-workers-rhel7 was removed from this repo, but tide is stuck on it.  @JoelSpeed Can you override?

**Comment by ashcrow** [comment]
(patch manager): Removing approval due to timing of the merge only. Next patch manager please consider re-approving once the window re-opens.

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-workers-rhel7

This test has been removed

**Pull request merged**
