### PR TITLE
Bug 2087039: Update dependencies to K8s 1.24

### PR DESCRIPTION
**Pull request by damdo**
Update the dependencies to K8s 1.24.

**Note**:
Since ConfigMapLock has been deprecated since K8s 1.17, and has been removed since 1.24, we need to migrate to a different locking mechanism, i.e. LeaseLock.

Before doing so, to avoid multiple replicas becoming leader, this has to be migrated to a transitionary MultiLock (ConfigMapsLeasesResourceLock), before moving to LeaseLock in the following release. The Reasoning on why this is the case is available here: https://github.com/kubernetes-sigs/controller-runtime/blob/196828e54e4210497438671b2b449522c004db5c/pkg/manager/manager.go#L144-L175

### CODE REVIEW

**Comment by damdo** [comment]
/hold
Still manually testing some things around leader election.

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-operator 

The last test results show that the tests passed, but it failed on tear down.

**Pull request merged**
