### PR TITLE
[OCPBUGS-380] Ensure the phase transition metric only updates when the phase changes

### PR DESCRIPTION
**Pull request by JoelSpeed**
The metric has been being updated every time the Machine reconciles, this isn't particularly helpful and means the data isn't useful. To fix this, only update the metric when the phase has actually changed for a machine. This should make the data accurate

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold cancel

QE verified this on Azure

**Comment by JoelSpeed** [comment]
/hold cancel

Have reviewed the tests and we know about the failures here, there's a PR open to the E2E to fix the issue.
/override ci/prow/e2e-aws-operator

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-ovn

Test failures are unrelated

**Pull request merged**
