### PR TITLE
Bug 1801228: Update BareMetalHost CRD

### PR DESCRIPTION
**Pull request by sadasu**
BareMetalHost CRD now needs a new field to disable certificate checking
to be able to test RedFish deployments.

### CODE REVIEW

**Comment by sadasu** [comment]
The CRD in baremetal_operator has already been updated as part of https://github.com/openshift/baremetal-operator/pull/51.

**Comment by enxebre** [comment]
I'd suggest someone from metal3 team to review this PR and also share some context and references on the PR description, is there any source of truth/enhancement doc so we can understand the change to review, why wasn't this needed before, why it is now, what's the plan forward? From mao mechanics pov this looks ok.
/approve

**Comment by sadasu** [comment]
Metal3 is adding support for the Redfish protocol to manage baremetal servers. (Before Redfish support was added, it was using IPMI to manage baremetal servers.)  There are some scenarios (especially lab testing environments) where self-signed certificates are used on the servers and Redfish connections fail because of strict certificate checking. To circumvent this issue, a config to disable certificate checking has been added to allow for self-signed certificates.

@stbenjam @dhellmann @hardys could you please take a look at the changes and the above comment I provided in response to comment https://github.com/openshift/machine-api-operator/pull/489#issuecomment-584541421 from @enxebre

**Pull request merged**
