### PR TITLE
Bug 1948719: update dependencies to 1.21

### PR DESCRIPTION
**Pull request by elmiko**
This change updates the go.mod and related vendor files to the
kubernetes 1.21 baseline. This was achieved by updating some of the
entries in go.mod and then running `make vendor`.

The updates to go.mod were as follows:
```
github.com/openshift/api master
github.com/openshift/client-go master
github.com/openshift/library-go master
k8s.io/kubectl v0.21.0
sigs.k8s.io/controller-runtime 0.9.0-alpha.1
```

Then ran `make vendor` to produce the update.

### CODE REVIEW

**Comment by elmiko** [comment]
putting a hold on this so that ci doesn't run while i do some investigation
/hold

**Comment by elmiko** [comment]
guess that didn't really do what i wanted... lol
/hold cancel

@JoelSpeed curious for your thoughts on the second commit, not sure if the hacky approach was the best for these tests.

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Pull request merged**
