### PR TITLE
Revendor cluster api

### PR DESCRIPTION
**Pull request by enxebre**
Accommodate https://github.com/openshift/cluster-api/pull/34
https://github.com/openshift/cluster-api-actuator-pkg/pull/73
https://github.com/openshift/installer/pull/1688
https://github.com/openshift/cluster-api-provider-aws/pull/206

### CODE REVIEW

**Comment by ingvagabund** [comment]
```
go test -timeout 60m \
	-v ./vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e \
	-kubeconfig ${KUBECONFIG:-~/.kube/config} \
	-machine-api-namespace ${NAMESPACE:-openshift-machine-api} \
	-ginkgo.v \
	-args -v 5 -logtostderr true
# github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go:961:12: unknown field 'Versions' in struct literal of type "github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1".MachineSpec
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go:984:12: unknown field 'Versions' in struct literal of type "github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1".MachineSpec
vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go:1079:14: unknown field 'Versions' in struct literal of type "github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1".MachineSpec
FAIL	github.com/openshift/machine-api-operator/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e [build failed]
```

**Comment by enxebre** [comment]
```
level=info msg="Make sure ssh-agent is running, env SSH_AUTH_SOCK is set to the ssh-agent's UNIX socket and your private key is added to the agent."
level=info msg="Use the following commands to gather logs from the cluster"
level=info msg="ssh -A core@35.173.221.184 '/usr/local/bin/installer-gather.sh 10.0.140.162 10.0.148.166 10.0.160.26'"
level=info msg="scp core@35.173.221.184:~/log-bundle.tar.gz ."
level=fatal msg="failed to wait for bootstrapping to complete: timed out waiting for the condition"
```
/retest

**Comment by spangenberg** [comment]
```
Apr 29 17:39:21.339: Could not reach HTTP service through a53413fc16aa511e9bcfc12feb060750-705095622.us-east-1.elb.amazonaws.com:80 after 2m0s
```

/retest

**Pull request merged**
