### PR TITLE
Bug 2022838: GCP CI runs are complaining about APIs not being enabled

### PR DESCRIPTION
**Pull request by elmiko**
disable the API service check

### CODE REVIEW

**Comment by wking** [comment]
openshift-dns-operator `TargetDown` on an unrelated platform is orthogonal to this PR.  Retesting this required presubmit:

/test e2e-vsphere-upgrade

**Comment by wking** [comment]
Unrelated platform, but retest to see if we can avoid the AWS quorum-loss recovery timeouts:

/test e2e-aws-disruptive

**Comment by sdodson** [comment]
/override ci/prow/e2e-vsphere-upgrade
/override ci/prow/e2e-metal-ipi-virtualmedia
/override ci/prow/e2e-metal-ipi-ovn-ipv6
/override ci/prow/e2e-aws-disruptive
Irrelevant.

**Pull request merged**
