### PR TITLE
fix image-references for ironic-machine-os-downloader

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@elfosardo you did the name in openshift/release, can you review/confirm this is correct?
https://github.com/openshift/release/commit/fcc0bd1085c4bd710251386cedfdf14e5554cdd2

cc @enxebre

**Comment by mrunalp** [comment]
Looks fine to me but would have to check with others. cc: @michaelgugino

**Comment by stbenjam** [comment]
A much more substantial change is needed: https://github.com/openshift/machine-api-operator/pull/452

**Comment by sosiouxme** [comment]
superseded by https://github.com/openshift/machine-api-operator/pull/452/files

**Pull request closed without merging**
