### PR TITLE
remove hard-coding of AWS instance type

### LINKED ISSUE #85: Configurable instance types on AWS?
This could be me just not understanding how this operator is wired up, but it looks like you currently hard-code `m4.large` [here][1].  I'd have expected that information to come from [the installer][2] via the [cluster config][3].  Am I missing something?  Or is this just future work that hasn't happened yet?

[1]: https://github.com/openshift/machine-api-operator/blob/f2689d525af210706c152075a7570cd60855999d/machines/aws/worker.machineset.yaml#L48
[2]: https://github.com/openshift/installer/blob/52ddd51ae6bbab5a795cd08ca59c41dd33a643c9/pkg/types/machinepools.go#L32-L34
[3]: https://github.com/openshift/installer/blob/52ddd51ae6bbab5a795cd08ca59c41dd33a643c9/pkg/asset/manifests/operators.go#L90-L96

### PR DESCRIPTION
**Pull request by trawler**
resolves #85

### CODE REVIEW

**Comment by enxebre** [comment]
is the installer passing this value? what happens if this is empty?

**Comment by enxebre** [comment]
@trawler this is probably a legit fail based on my comment above as the test config don't set that value

**Comment by enxebre** [comment]
@trawler The installer is currently not setting this value, we'll want a counter part PR to set this from the installer config.
How everr looking at the actuator https://github.com/openshift/cluster-api-provider-aws/blob/master/cloud/aws/actuators/machine/actuator.go#L381
```type RunInstancesInput struct``` would use a default value 
```
// The instance type. For more information, see Instance Types (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html)
	// in the Amazon Elastic Compute Cloud User Guide.
	//
	// Default: m1.small
	InstanceType *string `type:"string" enum:"InstanceType"
```
and the e2e-aws shows green, so not sure why our e2e was failing when the value was not set, can you please verify this?

**Comment by trawler** [comment]
> @trawler The installer is currently not setting this value, we'll want a counter part PR to set this from the installer config.
> How everr looking at the actuator https://github.com/openshift/cluster-api-provider-aws/blob/master/cloud/aws/actuators/machine/actuator.go#L381
> `type RunInstancesInput struct` would use a default value
> 
> ```
> // The instance type. For more information, see Instance Types (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html)
> 	// in the Amazon Elastic Compute Cloud User Guide.
> 	//
> 	// Default: m1.small
> 	InstanceType *string `type:"string" enum:"InstanceType"
> ```
> and the e2e-aws shows green, so not sure why our e2e was failing in your previews commit when the value was not set in the config, can you please verify this to ensure there's no gaps from installer->actuator?

@enxebre I can confirm that when the instanceType is not being set, installation fails with this reply from the server:
`time="2018-10-11T12:55:03Z" level=error msg="error creating EC2 instance: InvalidParameterValue: Invalid value '' for InstanceType.\n\tstatus code: 400, request id: 7b516eca-f3f4
-40cb-b6c7-5d3b87057ccb" controller=awsMachine machine=openshift-cluster-api/worker-xkpbr`

I'm not sure why the comment you quoted claims to set a default value, but actually, the aws-sdk will fail the install for an empty `InstanceType` with an InvalidParams error: 
https://github.com/aws/aws-sdk-go/blob/master/service/ec2/api.go#L23606

`// Validate inspects the fields of the type to determine if they are valid.
func (s *AllocateHostsInput) Validate() error {
  invalidParams := request.ErrInvalidParams{Context: "AllocateHostsInput"}
  if s.AvailabilityZone == nil {
    invalidParams.Add(request.NewErrParamRequired("AvailabilityZone"))
  }
  if s.InstanceType == nil {
    invalidParams.Add(request.NewErrParamRequired("InstanceType"))`

**Comment by trawler** [comment]
e2e-aws test failing for: 
```
* aws_eip.nat_eip.3: Error creating EIP: AddressLimitExceeded: The maximum number of addresses has been reached.
	status code: 400, request id: 2f81367d-af16-4462-b41e-84b7fc3ba5a2
```

**Comment by wking** [comment]
> is the installer passing this value? what happens if this is empty?

Where do we want the default value to live?  If it's here, that's great.  If it's in the installer, what happens if a user later bumps the config to remove the property (in an attempt to revert to the default value)?  Or will tgat sort of adjustment be blocked somehow?

**Comment by wking** [comment]
Also, it may not be worth sinking time into this if [the installer starts creating worker machine-sets directly][1].

[1]: https://github.com/openshift/installer/pull/451#issuecomment-428625419

**Comment by enxebre** [comment]
closing as specs are now moved to the installer

**Pull request closed without merging**
