### PR TITLE
install/0000_90_machine-api-operator_04_alertrules: Use '!~' for MachineWithNoRunningPhase

### PR DESCRIPTION
**Pull request by wking**
b13dbe9949 (#807) added `|Deleting`.  But to move from "not equal" to "regexp does not match" we need to match that with `!~`.

/assign @elmiko

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Comment by elmiko** [comment]
/retitle Bug 1974758: install/0000_90_machine-api-operator_04_alertrules: Use '!~' for MachineWithNoRunningPhase

**Comment by vrutkovs** [comment]
Seems worth bringing this to 4.7 as well

/cherry-pick release-4.7

**Pull request merged**
