### PR TITLE
Bug 1883497: Fix missing logs due to mixed klog versions 

### PR DESCRIPTION
**Pull request by JoelSpeed**
This makes klog consistent with the core of the Kubernetes project (as 
of v1.19) which used klog/v2.

While on differing versions we will lose logs (only one version will 
bind the correct flag value) so we should upgrade to v2 to ensure all 
logs are being printed correctly.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/hold cancel

This is now ready to merge

**Review by alexander-demichev — APPROVED** [review]
/approve

**Pull request merged**
