### PR TITLE
Bug 1934216: reuse mgr client in webhooks

### PR DESCRIPTION
**Pull request by michaelgugino**

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
this makes sense to me, thanks Mike!
/approve

**Comment by wking** [comment]
[`AlertmanagerMembersInconsistent`][1] and [brief `kubernetes-api-available-new-connections` disruption][2] seem unrelated.

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/817/pull-ci-openshift-machine-api-operator-master-e2e-aws/1366884636721942528
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/817/pull-ci-openshift-machine-api-operator-master-e2e-aws-upgrade/1366884636801634304

**Comment by wking** [comment]
[`kubelet terminates kube-apiserver gracefully` failure][1] unrelated.

/retest

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/817/pull-ci-openshift-machine-api-operator-master-e2e-aws/1366935850562097152

**Comment by JoelSpeed** [comment]
So having looked at the bug, the problem with the code as is in master today is that we create a new rest mapper for each new client. When the client is created, because we don't pass a restmapper in the options, it creates a new dynamic restmapper and hence, performs the discovery process many times.

While this change works, it does change the behaviour of the webhooks slightly. The client returned by the manager is a cached client, where the clients currently in use by the webhooks are uncached. If we care about this change, we can continue constructing the new client but use the managers rest mapper in the options instead of leaving it empty.

```
c, err := client.New(cfg, client.Options{
	Scheme: mgr.GetScheme(),
	RestMapper: mgr.GetRESTMapper(),
})	
if err != nil {	
	return nil, fmt.Errorf("failed to build kubernetes client: %v", err)	
}
```

**Comment by michaelgugino** [comment]
@JoelSpeed are there any downsides to the cached client in this context?  The machines/machinesets we're defaulting/validating are embedded in the request rather than fetched, so those shouldn't be stale.  I think we're only using the client to fetch the user data secrets.

**Comment by JoelSpeed** [comment]
The only downside I can think is that it will start an informer (if there isn't one already) watching secrets. Which, in this case, because the manager is restricted to the machine api namespace, will only list the secrets in the MAPI namespace. So, there may be some bloat in terms of memory usage if there were a lot of secrets, but possibly not an issue here.

If we were ever to use the machineset controller for multiple namespaces this would cause an issue

**Comment by michaelgugino** [comment]
@JoelSpeed either way is fine for me.  It seems like this change will work, but if you want to open another PR, that's fine too.  I just want something to merge today.

**Comment by JoelSpeed** [comment]
Let's merge this as it's closer, we can get the fix out and if it causes issues, we are aware of a way to optimise it in the future
/lgtm
/test e2e-aws

**Pull request merged**
