### PR TITLE
Bug 1994480: Update dependencies to K8s 1.22

### PR DESCRIPTION
**Pull request by JoelSpeed**
We should make sure our dependencies are up to date before the 4.9 code freeze

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Review by Fedosin — COMMENTED** [review]
Please update https://github.com/openshift/machine-api-operator/blob/master/.ci-operator.yaml#L4 accordingly

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-metal-ipi-ovn-dualstack

I don't understand why this test is being retested, it's not a required test

**Pull request merged**
