### PR TITLE
CFE-684: Update GCPCloudCredentials with TagUser role

### PR DESCRIPTION
**Pull request by bharath-b-rh**
PR is for updating CredentialRequest manifest of GCP with the TagUser role required for adding tags to GCP Compute Instances created by machine-api-provider-gcp.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
What's the motivation here? Why is this coming so late in the cycle? We are also trying to merge granular permissions (see https://github.com/openshift/machine-api-operator/pull/1178) for GCP into this release, the two will conflict.

Can you identify from this role, which permissions need to be added in the other PR to satisfy the requirements here?

**Comment by bharath-b-rh** [comment]
> What's the motivation here? 

These roles are required by `machine-api-provider-gcp` controller to add resource manager tags to Compute resources created by it.

> Why is this coming so late in the cycle? 

This is for the next release, it was in draft state, opened it for reviews for the next release.

> We are also trying to merge granular permissions (see https://github.com/openshift/machine-api-operator/pull/1178) for GCP into this release, the two will conflict
> Can you identify from this role, which permissions need to be added in the other PR to satisfy the requirements here?

Below additional permissions are required for managing tags
- compute.disks.createTagBinding
- compute.instances.createTagBinding
- resourcemanager.tagValues.get
- resourcemanager.tagValues.list

**Comment by JoelSpeed** [comment]
Changes look good, can we get some QE pre-merge validation on this feature before we merge though please. I can tag once QE are happy

**Comment by jianli-wei** [comment]
@JoelSpeed QE pre-merge testing had passed (see [comment](https://issues.redhat.com/browse/CORS-2990?focusedId=23858042&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23858042)), thanks!

**Pull request merged**
