### PR TITLE
Bug 1880110: vSphere: Fix double create

### PR DESCRIPTION
**Pull request by michaelgugino**
Currently, some unknown condition can cause the
actuator to double create the clone task.  The
suspected reason is an eventual consistency problem
in the vSphere API which results in the task
object returned by the API as being nil immediately
after creation.

This commit ensures we only ever create a single
clone task.

### CODE REVIEW

**Comment by enxebre** [comment]
/retest
/approve
@michaelgugino can you please open a ticket and PR for https://github.com/kubernetes-sigs/cluster-api-provider-vsphere
PTAL @alexander-demichev @Danil-Grigorev @JoelSpeed

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Comment by michaelgugino** [comment]
> @michaelgugino can you please open a ticket and PR for https://github.com/kubernetes-sigs/cluster-api-provider-vsphere


@enxebre upstream is not affected by this on latest code: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/de70ff05039df7ab15a4ba11a3f559f4e92f9df7/pkg/services/govmomi/service.go#L61

Their reconcile loop is much different than ours, they always check for existing tasks before taking any other action.

**Review by elmiko — APPROVED** [review]
i like the extra comments you added, it helps readability for me.

/lgtm

**Pull request merged**
