### PR TITLE
OCPCLOUD-1725: Add GCP custom roles

### PR DESCRIPTION
**Pull request by JoelSpeed**
Reverts openshift/machine-api-operator#1097 which reverted the addition of these roles originally.
This moves the the permissions from generic roles including many unusued permissions to a pruned and specific list of only the permissions we need.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Per email from @jstuever, putting this on hold until an issue is resolved in upgrades
/hold

**Review by damdo — COMMENTED** [review]
/approve

**Review by damdo — COMMENTED** [review]
/lgtm

**Review by elmiko — COMMENTED** [review]
/approve

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold 

Comment from Milind on https://issues.redhat.com/browse/OCPBUGS-25654 suggests there's a missing permission for deregistering instances from target groups, required for CPMS operation

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
