### PR TITLE
Bug 1866719: Keep machine.nodeRef even if node was marked for deletion

### PR DESCRIPTION
**Pull request by n1r1**
If node get deleted, nodelink controller will [remove the nodeRef](https://github.com/openshift/machine-api-operator/blob/master/pkg/controller/nodelink/nodelink_controller.go#L261-L262) from the machine.
It will happen only if there's something that delays the deletion, such as node finalizer. Otherwise, nodelink controller won't be notified that the node was deleted.

It means that we could reach different outcome, depends on the time taken for a node to be deleted.
If node was deleted immediately - nodeRef will stay on the machine.
If there's some delay (e.g. due to finalizer) - nodeRef will be deleted

It can also create a race with providers who put finalizer on the node, then can't determine which machine was associated with that node (see https://bugzilla.redhat.com/show_bug.cgi?id=1866719 )

Moreover, Machine in its lifecycle should have only one node. Thus, there's no reason to remove that nodeRef.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Are there any tests that will need updating to reflect this change? If not, are there tests we can add to ensure that the noderef remains when a node is removed?

**Comment by n1r1** [comment]
> Are there any tests that will need updating to reflect this change? 
doesn't look like it

> If not, are there tests we can add to ensure that the noderef remains when a node is removed?
Yep. good point. I've added a testcase to cover this flow

**Comment by enxebre** [comment]
>/test goimports

goimports doesn't like the change https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/669/pull-ci-openshift-machine-api-operator-master-goimports/1291332427964223488

**Comment by n1r1** [comment]
> goimports doesn't like the change https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/669/pull-ci-openshift-machine-api-operator-master-goimports/1291332427964223488

Thanks. Fixed.

**Pull request merged**
