### PR TITLE
Bug 1796412: cluster-reader is unable to view machine resources

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Add cluster-reader to machine.openshift.io group
- Remove role from an incorrect location, where it was not taken by CVO

### CODE REVIEW

**Comment by Danil-Grigorev** [comment]
After deploying with cluster-bot, freshly installed cluster contains desired role-binding:

**Comment by JoelSpeed** [comment]
I think we can drop the separate cluster-reader rbac file once it's included in the main rbac file as you've done, otherwise I think it's good. We only need it in the install folder the once, and we won't need it in config either

**Comment by Danil-Grigorev** [comment]
@JoelSpeed I removed redundant file with RBAC, sorry, didn't notice that at once

**Comment by Danil-Grigorev** [comment]
Accidentally closed PR, going to do robot job for a while 🥺 /retest

**Pull request merged**
