### PR TITLE
NO-JIRA: Updates MachineSet tests to use GenerateName

### PR DESCRIPTION
**Pull request by theobarberbany**
Use GenerateName when creating MachineSet instances to avoid test flakes.

Turs out the DeleteAll call in the cleanup function is async, so occasionally we were seeing test failures where the instance name was being reused, but the previous instance had not deleted yet.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
> Turs out the DeleteAll call in the cleanup function is async, so occasionally we were seeing test failures where the instance name was being reused, but the previous instance had not deleted yet.

You could add a wait to check to see that all of the resources have gone, but, this solution also works

**Comment by theobarberbany** [comment]
> You could add a wait to check to see that all of the resources have gone, but, this solution also works
I wonder, would a wait be better? I was going along the lines of not blocking the next test with this approach.... not that it matters with 2h e2es 😂

**Comment by JoelSpeed** [comment]
> I wonder, would a wait be better?

Typically its best practice not to end your test until you've cleaned up all of the resources that you created as a part of your test. If the util doing the delete all isn't waiting, perhaps it should be?

**Pull request merged**
