### PR TITLE
OCPBUGS-12626: Update golang.org/x/net dependency

### PR DESCRIPTION
**Pull request by JoelSpeed**
This updates the golang.org/x/net/http2 dependency to the latest version to mitigate reported CVEs in earlier versions of the code.

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
> machinehealthcheck_controller_test.go:3115: Test case: recentlyUnhealthy. Expected RequeueAfter between: 5m0s and 5m1s, got: {false 4m59.986349652s}

That seems like a rather fragile test case 🤔

**Pull request merged**
