### PR TITLE
Add volume type to represent shared volume for a Baremetal deployment

### PR DESCRIPTION
**Pull request by sadasu**
Create a volume type to represent the shared volume used by various containers in a Baremetal deployment. Also, the Baremetal CRD needs it ordering number bumped up by 1.

### CODE REVIEW

**Comment by stbenjam** [comment]
Can you remove WIP from commit message + title if this is ready to go? Looks good to me.

**Comment by enxebre** [comment]
>Also, the Baremetal CRD needs it ordering number bumped up by 1.
can you elaborate why in the description?

**Comment by russellb** [comment]
> > Also, the Baremetal CRD needs it ordering number bumped up by 1.
> can you elaborate why in the description?

I've pinged @sadasu on slack to ask, but AFAICT, it looks like it's just cosmetic, and not fixing anything

**Comment by enxebre** [comment]
the local volume will be lost during rolling upgrades i.e during cluster upgrades, I assume you are good with that?

**Comment by russellb** [comment]
> the local volume will be lost during rolling upgrades i.e during cluster upgrades, I assume you are good with that?

Yep - it's designed around losing all of this data anytime, just need to share some stuff between a handful of containers while they run

**Comment by russellb** [comment]
confirmed that the number change is just cosmetic btw @enxebre

**Comment by sadasu** [comment]
> > Also, the Baremetal CRD needs it ordering number bumped up by 1.
> 
> can you elaborate why in the description?

@enxebre I had originally picked #12 in the filename (next seriel number that was available) and then a merge went just before mine that had grabbed that #. I missed this detail in my original commit and rebase won't flag that. I bumped the # in my filename to #13 to accommodate to accommodate the file naming convention.

**Comment by enxebre** [comment]
@sadasu cool see for more input on how ordering works https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/operators.md#what-is-the-order-that-resources-get-createdupdated-in

**Pull request merged**
