### PR TITLE
Move to setup-envtest

### PR DESCRIPTION
**Pull request by alexander-demichev**
This PR removes kubebuilder envtest setup script and introduces the usage of setup-envtest binary.

### CODE REVIEW

**Comment by lobziik** [comment]
did you try `go install`?

https://pkg.go.dev/sigs.k8s.io/controller-runtime/tools/setup-envtest#section-readme

**Comment by elmiko** [comment]
i tried testing this locally by running `make unit`, but i got a bunch of errors about being unable to start the control plane. is the expectation that i should be able to run this?

**Pull request closed without merging**
