### PR TITLE
Updating ose-machine-api-operator images to be consistent with ART

### PR DESCRIPTION
**Pull request by lobziik**
Cherry-picked from #1035 

Apply `go fmt` related changes in follow up commit

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/approve
/lgtm

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-operator

The remaining failed autoscaler tests are already being investigated, the rest of the tests passed so I'm content this change isn't breaking anything

**Pull request merged**
