### PR TITLE
[release-4.11] Bug 2105382: Add a validation webhook for Nutanix MachineProviderConfig

### PR DESCRIPTION
**Pull request by elmiko**
this is a cherry-pick of #1034 and #1038 combined. i am bringing them into a single PR to help work around some ordering issues with the backports, the bugzillas, and the bots, with the goal of making this easier to review and merge.

### CODE REVIEW

**Comment by elmiko** [comment]
cc @thunderboltsid @yanhua121 , i've created this to help a little

**Comment by yanhua121** [comment]
> cc @thunderboltsid @yanhua121 , i've created this to help a little

The code changes look good to me.

**Comment by miyadav** [comment]
Tested and passed - https://bugzilla.redhat.com/show_bug.cgi?id=2105382 

/lgtm
/label qe-approved

**Pull request merged**
