### PR TITLE
[release-4.4] Bug 1896725: Drop cvo as a library in favour of library-go for applying resources

### PR DESCRIPTION
**Pull request by JoelSpeed**
The CVO version of the `ApplyDeployment` method is causing panics in CI (eg in https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-rollback-4.4-to-4.5/1324097015897919488).

We aren't seeing this in later versions which have been updated to use the library-go version of `ApplyDeployment`, so this PR updates the 4.4 branch to include the newer library go version

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Comment by sdodson** [comment]
approving on behalf of @ecordell

**Pull request merged**
