### PR TITLE
[OCPCLOUD-1173] Add related objects to Cluster Operator

### PR DESCRIPTION
**Pull request by alexander-demichev**
Add related objects to Cluster Operator.

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Can we include these ones too https://github.com/openshift/machine-api-operator/blob/ef0edd3ca1c611724ca4b8055193406d22b8406b/pkg/operator/status.go#L186-L207?

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
