### PR TITLE
Bug 1909108: Upgrade dependencies to controller-runtime v0.7.0 and K8s 1.20

### PR DESCRIPTION
**Pull request by JoelSpeed**
This PR bumps K8s dependencies to 1.20 and controller runtime to the latest v0.7.0 release.

This is also a follow up for #697 which swaps our own `responseWithWarnings` method for one that has been introduced into controller runtime.

Breaking changes due to the controller runtime bump are included in the second commit, breaking changes due to the K8s bump are included in the third commit

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
/lgtm

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold

This PR bumps controller runtime which in turn has migration logic to move from configmaps to leases for leader election.

We either need to explicitly choose configmaps for the leases and migrate later or add the new RBAC that's required

```
leaderelection.go:325] error retrieving resource lock openshift-machine-api/cluster-api-provider-machineset-leader: leases.coordination.k8s.io "cluster-api-provider-machineset-leader" is forbidden: User "system:serviceaccount:openshift-machine-api:machine-api-controllers" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-machine-api"
```

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
