### PR TITLE
CFE-684: Update openshift/api package to latest version

### PR DESCRIPTION
**Pull request by bharath-b-rh**
PR is for updating the openshift/api package to the latest version which contains the API changes for supporting GCP tags in Machine and MachineSet APIs made in https://github.com/openshift/api/pull/1506

Updating openshift/api requires updating below packages to latest as well
- k8s.io/client-go
- k8s.io/apimachinery
- k8s.io/api
- k8s.io/apiserver

### CODE REVIEW

**Comment by bharath-b-rh** [comment]
`ci/prow/golint` is failing with below error and requires replacing `klogr` package with `textlogger`. Should this be handled in this PR? Please suggest.
```
cmd/vsphere/main.go:199:17: SA1019: klogr.New is deprecated: this uses a custom, out-dated output format. Use textlogger.NewLogger instead. (staticcheck)
	ctrl.SetLogger(klogr.New())
	               ^
pkg/controller/machineset/machineset_controller_suite_test.go:39:17: SA1019: klogr.New is deprecated: this uses a custom, out-dated output format. Use textlogger.NewLogger instead. (staticcheck)
	logf.SetLogger(klogr.New())
	               ^
```

**Comment by RadekManak** [comment]
As this PR only updates the vendor. I suggest you wait for cloud team to handle the k8s 1.29 bump. It will be done in few days.

**Comment by RadekManak** [comment]
/close
I have opened #1208

**Pull request closed without merging**
