### PR TITLE
OCPCLOUD-1769: Make machine phases public consts

### PR DESCRIPTION
**Pull request by cjschaef**
Rather than forcing machine providers to replicate the machine
phases, if needed, the phases should be made public consts instead.

Related: https://issues.redhat.com/browse/OCPCLOUD-1769

Requires: https://github.com/openshift/api/pull/1358

### CODE REVIEW

**Comment by cjschaef** [comment]
Requires API changes to merge so the go mod can be updated properly.
/hold

**Comment by cjschaef** [comment]
https://github.com/openshift/api/pull/1358 has merged.
I will rebase and update go mod

**Comment by cjschaef** [comment]
Rebased and tested locally with custom image.

**Comment by cjschaef** [comment]
Rebase completed after local testing. Linting looks good, should be ready for review now.
/unhold

**Comment by cjschaef** [comment]
Failures appear to be unrelated to this change, TF or secret genration, etc.
/retest

**Comment by cjschaef** [comment]
Looks like more conformance test failures, retrying
/retest

**Comment by elmiko** [comment]
some of the test errors look like permission issues, which is concerning but probably unrelated to these changes.

```
Error from server (Forbidden): imagestreams.image.openshift.io "release" is forbidden: User "system:serviceaccount:ci-op-b5z6y3vk:e2e-aws-ovn-upgrade" cannot get resource "imagestreams" in API group "image.openshift.io" in the namespace "ci-op-b5z6y3vk"
```

the azure test failure looks interesting, but also unrelated to this change. likewise for libvirt.

**Comment by elmiko** [comment]
i looked at the history for the e2e-azure-operator test and it seems to be failing in different ways for each run, i would chalk this up to flakes on the infrastructure.

**Pull request merged**
