### PR TITLE
[OCPCLOUD-977] Bump scripts to Go 1.15

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Unblocks https://github.com/openshift/release/pull/13785

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Review by alexander-demichev — APPROVED** [review]
/lgtm

**Review by elmiko — APPROVED** [review]
/lgtm

**Comment by elmiko** [comment]
@Danil-Grigorev looks like we might need a rebase here

**Comment by Danil-Grigorev** [comment]
/hold cancel

Another LGTM is needed :D

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request closed without merging**
