### PR TITLE
Fix dockerfile to copy release manifests

### PR DESCRIPTION
**Pull request by vikaschoudhary16**

### CODE REVIEW

**Comment by enxebre** [comment]
with this all manifests including those not needed for install end up in manifests/ is that expected?
are only those with a given name convention used by the payload?

**Comment by vikaschoudhary16** [comment]
> with this all manifests including those not needed for install end up in manifests/ is that expected?
are only those with a given name convention used by the payload?

Need to verify if deleting others is unharmful. Or we can remove those in follow-up PR as well.

**Comment by paulfantom** [comment]
lgtm

**Comment by enxebre** [comment]
hey @vikaschoudhary16 please let's ensure we do resolve all unknowns in this PR so after merging we are included in the payload, thanks!

**Pull request merged**
