### PR TITLE
OCPBUGS-24277: Update reference URL

### PR DESCRIPTION
**Pull request by nrb**
Update URL after docs refactor.

Manual cherry-pick to avoid a duplicated Jira issue.

### CODE REVIEW

**Comment by elmiko** [comment]
seems like it thinks there is a race in the unit tests, but i can't imagine how this change would cause that

/lgtm
/label backport-risk-assessed

/test unit

happy to approve just wanted to see if the unit test error would go away

**Comment by nrb** [comment]
/retest

I suspect the vsphere e2es are timing out, not really failing on this change.

**Pull request merged**
