### PR TITLE
Bug 1925276: Make sure phase is always set before creation

### PR DESCRIPTION
**Pull request by alexander-demichev**
Make sure the phase is always set before creation. 
Check if the phase is empty, set it to provisioned, requeue, and call Create() only when the phase is set. 
Based on: https://github.com/openshift/machine-api-operator/pull/793

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Can we ensure that there is a test case that covers this. Unit tests seem to have failed in this package for some reason so maybe this is already covered?

**Comment by elmiko** [comment]
that unit test failure looks odd

**Comment by JoelSpeed** [comment]
I was intrigued so had a look at the tests, it's because we count the expected create calls with our mock actuator, this fixes them https://github.com/JoelSpeed/machine-api-operator/commit/ff63232dc74a28fabd052b8a149d480f1ffbe6e7

**Comment by elmiko** [comment]
wow, good find!
/lgtm cancel

**Comment by alexander-demichev** [comment]
@JoelSpeed Thank! I was about to look at tests.

**Review by elmiko — APPROVED** [review]
/lgtm

**Pull request merged**
