### PR TITLE
OCPCLOUD-492: Leader election for machineSets, nodelink, vsphere and healthchecks

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Added leader election support for all outstanding controllers in MAO .

Using leader election will add stronger guarantees than we have today that only one controller is running at a time to protect against edge cases where the deployment replica could be increased or upgrades with permissive maxSurge.

Relevant provider PRs:
- https://github.com/openshift/cluster-api-provider-gcp/pull/85
- https://github.com/openshift/cluster-api-provider-aws/pull/315
- https://github.com/openshift/cluster-api-provider-azure/pull/122
- https://github.com/openshift/cluster-api-provider-openstack/pull/108
- https://github.com/openshift/cluster-api-provider-baremetal/pull/81
- https://github.com/openshift/cluster-api-provider-ovirt/pull/55
- https://github.com/openshift/machine-api-operator/pull/571

### CODE REVIEW

**Comment by enxebre** [comment]
It'd be nice to have a separate commit for each controllers?
Is there already a counter part PR that it's leveraging these flags?

**Comment by enxebre** [comment]
thanks for changing the commits, that makes reviewing dramatically easier.
Could you please rephrase them to use imperative mood compliant with https://chris.beams.io/posts/git-commit/#imperative.
i.e Add Leader election flags for...

**Comment by Danil-Grigorev** [comment]
@enxebre Feel free to LGTM

**Comment by enxebre** [comment]
/lgtm
/hold

this should break until the other PRs are merged.
Is there PRs for metal3, openstack and oVirt we can reference here?
Can we elaborate on the PR desc and last commit desc why are we doing this?

**Comment by enxebre** [comment]
@Danil-Grigorev can we please put a PR for http://github.com/openshift/cluster-api-provider-ovirt as well?

**Comment by enxebre** [comment]
@Danil-Grigorev  can we please also include the PR desc in the commit message https://github.com/openshift/machine-api-operator/pull/571/commits/7ea5a321c3f20757100379f75ddd1238da0ca2d6

**Comment by enxebre** [comment]
>RouteHealthDegraded: route not yet available, https://console-openshift-console.apps.ci-op-cmksplwg-bfd7b.origin-ci-int-aws.dev.rhcloud.com/health returns '503 Service Unavailable'"

/retest

**Comment by stbenjam** [comment]
@enxebre @Danil-Grigorev  Why was this merged without the dependent cluster-api providers PR's all being merged in the description? This broke baremetal. Also, why wasn't e2e-metal-ipi run here? 

It's an optional job, but it should be run on anything that affects us. If it's not going to get run before merging things like this, then maybe we need to enable it to run all the time.

**Comment by enxebre** [comment]
sorry about that @stbenjam, I certainly thought the baremetal PR was merged. Please feel free to make that to job run on every PR while being not blocking.

**Pull request merged**
