### PR TITLE
Bug 1929721: Add SecurityProfile.EncryptionAtHost parameter to enable host-based VM encryption 

### PR DESCRIPTION
**Pull request by mjudeikis**
UPSTREAM: <carry>: openshift: add SecurityProfile.EncryptionAtHost parameter to enable host-based VM encryption

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Vendor update targets release-4.7 branch, LGTM
/approve
/lgtm
/retest

**Comment by derekwaynecarr** [comment]
(Patch-Manager) looking for clean CI signal.

/test e2e-vsphere

**Comment by mjudeikis** [comment]
@JoelSpeed Is the CI so flaky here or something I should be looking into? What is the state of this repo from the point of CI?

**Comment by mjudeikis** [comment]
@derekwaynecarr @JoelSpeed It is green! :face_with_head_bandage:

**Comment by JoelSpeed** [comment]
@mjudeikis vSphere based CI was only recently enabled and has been causing issues for us due to the capacity of the cluster and the number of machines we use during our tests. We have some work planned to look into this. Not sure why it was marked required when we know it's flaking this much though, I think we should change that until we know it's more reliable

**Pull request merged**
