### PR TITLE
Bug 2104642: fix the Machine validation webhook for nutanix providerSpec

### PR DESCRIPTION
**Pull request by yanhua121**
Bug 2105382: fix the Machine validation webhook for nutanix providerSpec
Add validation for fields: CredentialsSecret and UserDataSecret

### CODE REVIEW

**Comment by elmiko** [comment]
given the timing, we will have to target this bug for 4.12 and then backport it to 4.11. it shouldn't be a problem though.

**Comment by elmiko** [comment]
if this is in addition to @thunderboltsid patch, then we need to make this the bug https://bugzilla.redhat.com/show_bug.cgi?id=2104642

**Comment by elmiko** [comment]
doing a little more research, i think we just need to put this on the same bug as the previous change.

/retitle Bug 2104642: fix the Machine validation webhook for nutanix providerSpec

**Comment by miyadav** [comment]
Details of test added to : https://bugzilla.redhat.com/show_bug.cgi?id=2104642#c3

/lgtm 
/label qe-approved

**Comment by elmiko** [comment]
looks like we need https://github.com/openshift/machine-api-operator/pull/1036 to merge before the cherry-pick would work.

**Comment by elmiko** [comment]
i have created #1039 to address the backport of both PRs

**Pull request merged**
