### PR TITLE
Bug 1994820: Degrade operator on cluster bootstrap if not all Machines are Running

### PR DESCRIPTION
**Pull request by JoelSpeed**
This was discussed on the a recent cluster lifecycle arch call.

At the moment, we do not return any errors through the installation log if Machines fail to come up, even though these are often the cause of several issues that we see frequently in CI (eg route not ready because there aren't enough worker nodes).

To make things a little more obvious, this changed introduces a check for Machines during the initialization of the operator.
We require, in general, 2 worker machines to be running to host operators such as ingress.
If MachineSets are present in the cluster (this prevents errors on UPI or SNO), and there are fewer than 2 Machines in the running phase, this moves the operator into a degraded state until at least 2 Machines are running.
Once all Machines have been moved to running, this will move the operator to available and therefore, prevent the machine check from happening again in the future.

This means that we will now fail installations if fewer than 2 Machines come up. 

It should help when there are generic Machine/cloud errors to help users diagnose the underlying issue, by identifying Machine API as a failed component rather than just the route and auth operators.

I have tested this by simulating a failed Machine on a running cluster and then resetting the ClusterOperator so that the operator thinks it is initializing for a second time, as well as bootstrapping a cluster with only 1 MachineSet machine working, and 1 failing, and then eventually adding an extra working Machine.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
When the install failed it failed with:
```
ERROR Cluster operator machine-api Degraded is True with SyncingFailed: Failed when progressing towards operator: 4.11.0-0.ci.test-2022-05-23-152641-ci-ln-ghys7m2-latest because found 1 non running machine(s): jspeed-test-4l4vz-worker-us-east-2a-tb8zz
```
So this was a bright red and very obvious failure, though the rest of the cluster was up and running, need to double check our notes on what we thought about failing the cluster here

**Comment by JoelSpeed** [comment]
> it seems weird, but should we have some e2e test to exercise the failure state here? or perhaps a unit test with a mocked client?

I wanted to get consensus on the approach before working on testing. A unit test with envtest is probably the best idea I have so far, having an E2E is a bit trickier

**Comment by elmiko** [comment]
> I wanted to get consensus on the approach before working on testing. A unit test with envtest is probably the best idea I have so far, having an E2E is a bit trickier

+1, envtest sounds perfect to me

**Comment by elmiko** [comment]
we should discuss this further on standup, i think there are a few questions about the implementation.

**Comment by lobziik** [comment]
My main concern there is that we basing that "isInitializing" logic on a bunch of assumptions and basically have no guarantees that behaviour around will not change. Just looks a bit fragile and obscure to me.

If folks are agree i'm ok to go with this.

Code wise - lgtm.

**Comment by JoelSpeed** [comment]
> My main concern there is that we basing that "isInitializing" logic on a bunch of assumptions and basically have no guarantees that behaviour around will not change. If we could reference to some org-wide guidelies i would be way more calm about this. At the moment it just looks a bit fragile and obscure to me.

It is up to each operator to handle what happens when they start, and for now, to define when they vary the status of their ClusterOperator status.
In MAO, we have always, and should continue to, set, when we see an empty operator status, we set it to initializing until we have, for the first time, set it to available.
This logic is encoded into our operator and is therefore under our control. No one else should be interacting with our cluster operator status (CVO certainly doesn't) so there should be no way, in a running cluster, that the `Initializing` state comes back, unless someone manually manages to patch the status, which we always assume isn't supported.

Even if this mechanism does fail somehow, it's more likely to fail into the more open state (ie the check doesn't happen) so it's unlikely that we will end up degrading some customer cluster if something does get broken during some code changes.

This is basically an artifact of the cluster not having an initialising state defined, and that's ok, it's not meant to, it's a reconciling system. We just have to add this optimisation where we can based on what we have (IMO), if it works and helps some users, great, if it doesn't work, well, it's no worse than it is right now.

If anyone has some suggestion for how to make this more bulletproof I'm happy to investigate

**Comment by elmiko** [comment]
i appreciate the deep research @JoelSpeed , i think for now we should use this as is. if we get an improvement in the future we can revisit, or if we find a way to be more definitive about the initializing state.
/approve

**Review by elmiko — COMMENTED** [review]
bot is acting funny


/approve

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
