### PR TITLE
Make MAPO the default for OpenStack deployments

### PR DESCRIPTION
**Pull request by mdbooth**
This is the PR we will revert if it turns out to be a bad idea.

Going to run this past TRT first.

/hold

### CODE REVIEW

**Comment by stbenjam** [comment]
> Going to run this past TRT first.

If you're concerned about the impact on release blocking jobs, you can test this PR using `/payload`, e.g.: `/payload 4.11 ci blocking`

If there's a high likelihood of tanking the openstack jobs, you could open a preemptive approved revert for TRT to merge.

**Comment by JoelSpeed** [comment]
/approve

I will approve this and allow @mdbooth to pull the trigger on it, please do it at a sensible time so that if we break anything we can revert this in-hours

**Review by mandre — COMMENTED** [review]
Thanks @mdbooth.
/lgtm

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-upgrade

This change does not affect AWS, and the AWS CI is broken right now due to quota issues. I'm confident that merging this won't cause any issues with the failed AWS job. As the OpenStack E2E passed, I think this should be merged

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-vsphere-serial 

I'm content that this isn't going to break the existing workloads. Looking at the test results the standard blocking jobs have all passed, this shouldn't affect vsphere if it doesn't affect the other platforms

**Pull request merged**
