### PR TITLE
Bug 1814582: [release-4.4] [OCPCLOUD-774] Add Node startup timeout API field

### PR DESCRIPTION
**Pull request by JoelSpeed**
Cherry-pick of #501 

Replaces #523 as there were conflicts that needed to be manually resolved

### CODE REVIEW

**Comment by shawn-hurley** [comment]
@JoelSpeed 

This looks like a feature backports to me (addition of field to a type is what is concerning me.) Can we get justification for the need of this backport? 

/cc @mrunalp

**Comment by enxebre** [comment]
>This looks like a feature backports to me (addition of field to a type is what is concerning me.) Can we get justification for the need of this backport?

This is to bug fix a hardcoded narrow timeout consistently with what we do in higher releases. The API change is additive and backward compatible with existing default behaviour.

I think we can skip back porting this though and reconsider if we see a customer case coming through if that make sense @JoelSpeed @shawn-hurley .

**Comment by JoelSpeed** [comment]
Sounds reasonable to me! We can reopen if ever we get a customer case

**Pull request closed without merging**
