### PR TITLE
Remove not yet supported CRDs

### PR DESCRIPTION
**Pull request by enxebre**
As we go more stable we want to reduce the surface area for not yet supported resources until there's a solid e2e story for them.
Removing classes, ~~deployments~~ and clusters CRDs

### CODE REVIEW

**Comment by enxebre** [comment]
cc @derekwaynecarr @bison @ingvagabund @frobware

**Comment by ingvagabund** [comment]
/approve

not breaking anything afaik

**Comment by frobware** [comment]
Pretty sure this will break cluster-autoscaler.

**Comment by ingvagabund** [comment]
@frobware for the cluster-autoscaler + machine deployments

**Comment by ingvagabund** [comment]
> Pretty sure this will break cluster-autoscaler.

Machine deployments should be optional-ish, right?

**Comment by frobware** [comment]
> Machine deployments should be optional-ish, right?

They are and we disable looking for them by default. But we do create a machine deployment informer which will presumably now fail.

**Comment by frobware** [comment]
/hold

Pretty sure this will now break the autoscaler.

**Comment by ingvagabund** [comment]
/approve cancel

until properly resolved in CA

**Comment by enxebre** [comment]
keeping deployments for now
/hold cancel

**Pull request merged**
