### PR TITLE
add back controllers using latest provider image so using machine.openshift.io

### PR DESCRIPTION
**Pull request by enxebre**
- Add back controllers using latest provider image so using machine.openshift.io https://github.com/openshift/cluster-api-provider-aws/pull/147
- We have now all controllers for `cluster.k8s.io` and `machine.openshift.io`

### CODE REVIEW

**Comment by enxebre** [comment]
cc @bison @frobware @ingvagabund

**Comment by ingvagabund** [comment]
From the design point of view accepted.
/approve

**Pull request merged**
