### PR TITLE
[OCPCLOUD-1708]: Set default container for machine-api-operator

### PR DESCRIPTION
**Pull request by odvarkadaniel**
This PR sets a default container for MAO with a well-defined k8s annotation.

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Just wondering if we should also set the default container for the Machine API Controllers deployment?

https://github.com/openshift/machine-api-operator/blob/ef0c10617f20eacdae0be30d00f339c4b6fd19e8/pkg/operator/sync.go#L379

Probably want to default that to the `machine-controller` container I would say

**Pull request merged**
