### PR TITLE
update the baremetalhost crd for bootmode and rootdevicehints

### PR DESCRIPTION
**Pull request by dhellmann**
Update the CRD for BareMetalHost to the version that includes bootMode
and rootDeviceHints, 2 features added for the 4.6 release.

### CODE REVIEW

**Comment by zaneb** [comment]
I guess we should make it part of our process to update this whenever we sync the baremetal-operator from upstream.

**Comment by dhellmann** [comment]
> I guess we should make it part of our process to update this whenever we sync the baremetal-operator from upstream.

Ideally we could pull the CRD from the baremetal-operator repo as part of a build step instead, but yeah.

**Comment by dhellmann** [comment]
This has a LGTM but needs an approval.

**Pull request merged**
