### PR TITLE
WIP: Bring up BMO container last while deploying metal3

### PR DESCRIPTION
**Pull request by sadasu**
We need to ensure all othe containers are started before the
BMO container in a metal3 pod.

### CODE REVIEW

**Comment by stbenjam** [comment]
https://github.com/openshift/release/pull/8298 enables e2e-metal-ipi for MAO

**Comment by JoelSpeed** [comment]
I'm not convinced that moving the container to the end of the list makes it start last, as far as I'm aware all containers should be started at the same time no matter where they are in the list. Have you read/seen something that suggests otherwise?

Also, it would be good to understand why exactly you want this one to come up last, what is the reason for this?

**Comment by kirankt** [comment]
Hi

> I'm not convinced that moving the container to the end of the list makes it start last, as far as I'm aware all containers should be started at the same time no matter where they are in the list. Have you read/seen something that suggests otherwise?
> 
> Also, it would be good to understand why exactly you want this one to come up last, what is the reason for this?

+1.  Perhaps we should make use of readinessProbe within the BMO container to check whether the dependent containers have already come up successfully.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by sadasu** [comment]
> I'm not convinced that moving the container to the end of the list makes it start last, as far as I'm aware all containers should be started at the same time no matter where they are in the list. Have you read/seen something that suggests otherwise?
> 
> Also, it would be good to understand why exactly you want this one to come up last, what is the reason for this?

@JoelSpeed With the current implementation (without this current changes), we had noticed that baremetal-operator (which is one of the containers running in this pod) fails to provision some worker nodes because the other containers were not ready to handle requests. By moving the order of containers being added to the deployment, we were hoping that the other containers would get a head start in their initialization. Other than our local testing, we were hoping to see how this change in order affected CI runs (where we encountered this issue more frequently).

I am exploring the alternative suggested by @kirankt .

**Comment by sadasu** [comment]
This approach is incorrect. A different approach is being pursued to solve this issue within BMO.

**Pull request closed without merging**
