### PR TITLE
Bug 2107578: Fix while setting default processor value for Power VS platform

### PR DESCRIPTION
**Pull request by Karthik-K-N**
Avoid setting default values for processor when either int or string values are set

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
> Is there a bugzilla associated for this issue?

There isn't one for it yet

**Comment by Karthik-K-N** [comment]
> Is there a bugzilla associated for this issue?

Is this mandatory to have a bugzilla created for this.

**Comment by JoelSpeed** [comment]
Do we intend to backport this? If so, it should have a bug attached. Likewise, I would expect QE to want to check this, so having a bug means they can track it

**Comment by Karthik-K-N** [comment]
> Do we intend to backport this? If so, it should have a bug attached. Likewise, I would expect QE to want to check this, so having a bug means they can track it

Created a bugzilla

**Comment by JoelSpeed** [comment]
/lgtm
/approve

@Karthik-K-N Is this something that's blocking the 4.11 release?

**Comment by mkumatag** [comment]
> /lgtm /approve
> 
> @Karthik-K-N Is this something that's blocking the 4.11 release?

Not sure if this is blocking 4.11 release because we are just calling it as tech preview at the moment but I don't see a harm in delivering it in the 4.11 z stream if there is a scope for it!

**Comment by Karthik-K-N** [comment]
@JoelSpeed can we back port this to 4.11, If so how can we do that, Thanks

**Comment by elmiko** [comment]
we talked about this during our standup today, i am marking for backport but it will not make it in for the 4.11.0 release. it will go into the first z-stream for 4.11, unless this is a blocker for the release. we didn't think this should be a blocker, but if you think it should we can talk about it.

/cherry-pick release-4.11

**Comment by mkumatag** [comment]
> we talked about this during our standup today, i am marking for backport but it will not make it in for the 4.11.0 release. it will go into the first z-stream for 4.11, unless this is a blocker for the release. we didn't think this should be a blocker, but if you think it should we can talk about it.
> 
> /cherry-pick release-4.11

I'm okay for delivering this in the z stream release

**Comment by elmiko** [comment]
sounds good, thanks @mkumatag !

**Pull request merged**
