### PR TITLE
Bug 1854142: update baremetalhost crd to apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by dhellmann**
This updates the BareMealHost CRD to use v1 of the CRD type to provide
pruning of unknown fields.

### CODE REVIEW

**Comment by sadasu** [comment]
This change will keep the baremetalhost CRD in sync with what is in the baremetal-operator repo: https://github.com/metal3-io/baremetal-operator/blob/master/deploy/crds/metal3.io_baremetalhosts_crd.yaml

**Comment by hardys** [comment]
/retitle Bug 1854142: update baremetalhost crd to apiextensions.k8s.io/v1

**Pull request merged**
