### PR TITLE
[OCPCLOUD-1725]: GCP Credentials req. using new API field permissions

### PR DESCRIPTION
**Pull request by odvarkadaniel**
This PR removes all the `predefinedRoles` which give elevated permissions. We get those permissions and put them into the new API field `Permissions []string`. These permissions are known to thanks to the command `gcloud iam roles describe <role>` - this lists all the included permissions we want.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
> this lists all the included permissions we want.

Have you confirmed that this list is minimal? It's a very long list so i'd like to make sure that we do actually require each and every permission in the list. If you have, how did you do so?

**Review by lobziik — CHANGES_REQUESTED** [review]
+1 to @JoelSpeed's question.

I just quickly read through permissions list and things like 
```
    - "compute.licenses.create"
...
    - "compute.regionTargetHttpProxies.create"
...
    - "compute.targetGrpcProxies.create"
...
    - "compute.targetVpnGateways.create"
```
and so on - looks excessive to me.

**Comment by odvarkadaniel** [comment]
@lobziik, @JoelSpeed, These permissions are all the permissions that are tied to the `predefinedRoles` that used to be here. What I did is, I got rid of the duplicates from this extensive list of permissions (sorted them and deleted them using `awk`). Are you having concerns about some of the permissions being 'sub-permissions' of other, because that didn't cross my mind while researching this. Will have to take a look into that.

**Comment by JoelSpeed** [comment]
@odvarkadaniel The concern is not about sub permissions, but rather granting more permissions than we need.

If you look at https://github.com/openshift/machine-api-provider-gcp/blob/main/pkg/cloud/gcp/actuators/services/compute/computeservice.go, this is an abstraction on the GCP API that we use within this project. You can see from this that we only make a very small number of API calls, and, that these then relate to the permissions you've got in this list.

I think we can slim the list down to reflect the API calls we actually make and that should get us to a minimal list of permissions. The upshot is, we don't want to give this permissions we don't need to give it.

There may some implicit permissions needed as part of creating the instances but we will need to research/test to check that we haven't regressed here.

**Comment by odvarkadaniel** [comment]
> @odvarkadaniel The concern is not about sub permissions, but rather granting more permissions than we need.
> 
> If you look at https://github.com/openshift/machine-api-provider-gcp/blob/main/pkg/cloud/gcp/actuators/services/compute/computeservice.go, this is an abstraction on the GCP API that we use within this project. You can see from this that we only make a very small number of API calls, and, that these then relate to the permissions you've got in this list.
> 
> I think we can slim the list down to reflect the API calls we actually make and that should get us to a minimal list of permissions. The upshot is, we don't want to give this permissions we don't need to give it.
> 
> There may some implicit permissions needed as part of creating the instances but we will need to research/test to check that we haven't regressed here.

Ok, got it now.

**Comment by JoelSpeed** [comment]
What's the state of this PR, are you happy with the reduced list that you've created? Do we want to get QE to review this pre-merge?

**Comment by odvarkadaniel** [comment]
This is not tested at all yet. Was in a bus. Have to take a look whether everything works as expected and whether there are some more permission we could reduce.

**Comment by odvarkadaniel** [comment]
As of now, this list of the permission should be minimal and nothing should be missing. Logs from e2e test look good. Only thing that is left is to test it myself on a GCP cluster. Can't do that with `Cluster Bot` now, because the bot doesn't have permission to create a custom role - we construct a custom role from the permission we give in the manifest. When I try to replace the whole `machine-api-operator`, I get some weird behavior that I couldn't resolve yet.

**Comment by JoelSpeed** [comment]
Changes look sensible, I'd like to see QE do some extended testing on this before we merge though

**Comment by elmiko** [comment]
> Changes look sensible, I'd like to see QE do some extended testing on this before we merge though

+1

**Pull request merged**
