### PR TITLE
Add manifest annotations for hosted deployment exclusions

### PR DESCRIPTION
**Pull request by csrwng**
Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

### CODE REVIEW

**Comment by csrwng** [comment]
/assign @bison 
This should be ready for merge

**Comment by enxebre** [comment]
thanks @csrwng, do we have any docs that we can reference in this commit desc yet?
Why aren't we excluding the manifests not included in this PR

**Comment by csrwng** [comment]
@enxebre not yet, given we’re still in the beta phase on hosted deployments of Openshift.

**Comment by csrwng** [comment]
We’re only excluding manifests that cause the operator to come up. In some cases, namespaces and other artifacts are still used by other components.

**Pull request merged**
