### PR TITLE
Kube 1.16

### PR DESCRIPTION
**Pull request by enxebre**
/hold
Needs:
https://github.com/openshift/machine-api-operator/pull/399
https://github.com/kubernetes-sigs/controller-runtime/pull/588
And openshift/cluster-api to get https://github.com/kubernetes-sigs/controller-runtime/pull/588

### CODE REVIEW

**Comment by ironcladlou** [comment]
P.S., my team got ahead of this by temporarily relying on the Go modules `replace` directive to depend on the upstream 1.16 PR fork. See [ingress-operator](https://github.com/openshift/cluster-ingress-operator/blob/master/go.mod#L43) for an example.

Seems safe enough to use on our master branch for a while.

**Comment by enxebre** [comment]
thanks @ironcladlou we also created https://github.com/kubernetes-sigs/controller-runtime/pull/618 which we are using here https://github.com/openshift/cluster-api/pull/76

**Comment by ironcladlou** [comment]
@enxebre 
>thanks @ironcladlou we also created kubernetes-sigs/controller-runtime#618 which we are using here openshift/cluster-api#76

Cool, thanks! Hopefully one of them gets in soon!

**Comment by enxebre** [comment]
closing in favour of https://github.com/openshift/machine-api-operator/pull/401

**Pull request closed without merging**
