### PR TITLE
OCPBUGS-10719: [release-4.11] - manual cp #1057 - machines stuck in provisioned or provisioning

### PR DESCRIPTION
**Pull request by miyadav**
creating it to see if it helps to test [early](https://github.com/openshift/machine-api-operator/pull/1057)  
Please provide inputs if time permits it is for - OCPBUGS-10719 , keeping it as draft only.
@elmiko @damdo @RadekManak @JoelSpeed

### CODE REVIEW

**Comment by miyadav** [comment]
based on manual test ran for the change on the cluster created using this PR  , marking it ready for review , PTAL when time permits.

**Comment by JoelSpeed** [comment]
A few errors in the static validation here that will need to be fixed before we can get a good set of test results, looks like the govet picked up some incompatible code change

**Comment by miyadav** [comment]
/retitle OCPBUGS-10719: [release-4.11] - manual cp #1057 - machines stuck in provisioned or provisioning

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
Unrelated failures, monitoring components creating too many watch channels
/retest-required

**Pull request merged**
