### PR TITLE
Bug 1925276: Set provisioning phase after attempting create

### PR DESCRIPTION
**Pull request by michaelgugino**
Setting the phase (or anything else) that causes a machine
object to be patched prior to recording the instance ID
can result in a double create.  This is because the requeue
from the initial phase will process before the cache is
updated with the instance ID.

### CODE REVIEW

**Review by elmiko — APPROVED** [review]
this makes sense to me, i just have a question about how the operations are done. is it possible to have the machine be created with the provisioning state? (just curious about the update action and sequence)
/lgtm

**Comment by JoelSpeed** [comment]
This change means that we won't set the phase to provisioning if the machine actuator create fails right?

As an alternative, what about checking if the phase is empty, setting it to provisioned and then requeueing straight away, so we only start creating when we have read the object as having provisioning already? I think that would solve the same issue and get around the possibility of cache issues /create failure right?

**Comment by michaelgugino** [comment]
@JoelSpeed you've been working on phases and whatnot, can you take this over?

**Pull request closed without merging**
