### PR TITLE
Bug 1880787: Remove changes required to deploy metal3 pods from MAO

### PR DESCRIPTION
**Pull request by sadasu**
cluster-baremetal-operator will take care of managing these
resources.

### CODE REVIEW

**Comment by stbenjam** [comment]
What do you think about removing the RelatedObjects from status.go and status_test.go?

https://github.com/openshift/machine-api-operator/blob/71aeab4ff840991c8569baf3817e8640e03a2dfe/pkg/operator/status.go#L203-L207

https://github.com/openshift/machine-api-operator/blob/71aeab4ff840991c8569baf3817e8640e03a2dfe/pkg/operator/status_test.go#L241-L246

**Comment by stbenjam** [comment]
/retitle Bug 1903275: Remove changes required to deploy metal3 pods from MAO

**Comment by stbenjam** [comment]
Let's use this PR as the fix for the CRD conflict between CBO and MAO.

/bugzilla refresh

**Comment by sadasu** [comment]
https://github.com/openshift/machine-api-operator/pull/767#issuecomment-736731045

@stbenjam I am not sure if we need that because capbm refers to the baremetalhost CR. I could try to make that change and test.

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Comment by stbenjam** [comment]
> [#767 (comment)](https://github.com/openshift/machine-api-operator/pull/767#issuecomment-736731045)
> 
> @stbenjam I am not sure if we need that because capbm refers to the baremetalhost CR. I could try to make that change and test.

Oh I see, that makes sense, it probably should stay as a related object then.

**Comment by stbenjam** [comment]
/lgtm

@michaelgugino Would you be able to approve or do we need to get someone else? Thanks!

**Comment by stbenjam** [comment]
There's an older bug for this.

/retitle Bug 1880787: Remove changes required to deploy metal3 pods from MAO

**Comment by wking** [comment]
[Previous e2e-aws-operator job][1]:

```
2020/12/02 14:06:29 Container test in pod e2e-aws-operator-test completed successfully
```

before getting hung up in a slow gather-extra step.  If this is [blocking promotions][2], maybe we should `/override ci/prow/e2e-aws-operator` instead of waiting for a retest to go through?  Maybe only if [this current job][3] fails?

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/767/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/1334112021976715264#1:build-log.txt%3A102
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1880787#c10
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/767/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/1334189157416701952

**Comment by wking** [comment]
/bugzilla refresh

to pick up the urgent tag.

**Comment by wking** [comment]
[e2e-aws-operator][1] failed install with `VPC: VpcLimitExceeded`, which is a CI-infra issue, orthogonal to this PR.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/767/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/1334189157416701952#1:build-log.txt%3A164

**Comment by stbenjam** [comment]
Overriding it sounds fine to us, we'll need an approver in MAO to actually do it: Maybe @JoelSpeed or @michaelgugino?

**Comment by wking** [comment]
[Most recent e2e-aws-operator failure][1] is:

```
Autoscaler should use a ClusterAutoscaler that has 12 maximum total nodes count and balance similar nodes enabled scales up and down while respecting MaxNodesTotal 
```

But both install and gather-extra worked fine this time 😆

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-operator/767/pull-ci-openshift-machine-api-operator-master-e2e-aws-operator/1334226822220484608

**Pull request merged**
