### PR TITLE
Fixup cluster operator

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Updates the following:

- bumps dependencies of openshift/api, client-go, cluster-version-operator
- updates machine-api-operator `ClusterOperator` resource to name `machine-api`
- adds a related object so `openshift-must-gather` when gathering diagnostic info can collect information from the `openshift-cluster-api` namespace.

See https://github.com/openshift/must-gather

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
/hold

pending merge of https://github.com/openshift/cluster-version-operator/pull/115

**Comment by derekwaynecarr** [comment]
@enxebre it's not obvious to me what is happening here, do you see an obvious change?

**Comment by enxebre** [comment]
@derekwaynecarr thanks a lot! pr looks good.
e2e-aws-operator needs this to land https://github.com/openshift/machine-api-operator/pull/201/commits/1e54d5e6e934c92a696b9bcf64cc1bc90aef891f which needs https://github.com/openshift/kubernetes-autoscaler/pull/29
I'll make sure this get merged asap

**Pull request merged**
