### PR TITLE
CORS-3648: Add the hyperdisk-balanced disk type

### PR DESCRIPTION
**Pull request by barbacbd**
** Add the hyperdisk-balanced disk type for gcp machines. 
** Add the test to validate the new type.

### CODE REVIEW

**Comment by nrb** [comment]
/label jira/valid-bug

Adding this label since this is a feature backport, not a bug.

**Comment by barbacbd** [comment]
Backport for feature: https://github.com/openshift/machine-api-operator/pull/1268

**Comment by sdodson** [comment]
/retitle CORS-3648: Add the hyperdisk-balanced disk type

**Comment by sdodson** [comment]
Just taking notes for future me. As to why there's not a 4.17 PR, #1268 merged before 4.17 was branched from master.

**Pull request merged**
