### PR TITLE
Remove deprecated test/integration in favor of ginkgo based conformance tests

### PR DESCRIPTION
**Pull request by ingvagabund**
New JJ: https://github.com/openshift/aos-cd-jobs/pull/1719

### CODE REVIEW

**Comment by enxebre** [comment]
@ingvagabund can you add a commit with `dep ensure -v` to remove the dropped devs

**Comment by ingvagabund** [comment]
>  can you add a commit with `dep ensure -v` to remove the dropped devs

which dropped devs?

**Pull request merged**
