### PR TITLE
BUG 1877743: Bump K8s dependencies to v1.19.0

### PR DESCRIPTION
**Pull request by JoelSpeed**
Our dependencies are out of date and should be on K8s 1.19.0 before the 4.6 release to match the rest of the core components. This PR updates all of the K8s and openshift depdendencies to include the lastest 1.19.0 release.

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Pull request merged**
