### PR TITLE
Revert 155 change crds definitions and rename providerConfig to providerSpec

### PR DESCRIPTION
**Pull request by ingvagabund**
Reverting https://github.com/openshift/machine-api-operator/pull/155 and renaming `providerConfig` to `providerSpec`

Plus, building on top of https://github.com/openshift/machine-api-operator/pull/169.

**TODO**
- [x] providerConfig removed from Installer: https://github.com/openshift/installer/pull/1027
- [x] providerConfig removed from console: https://github.com/openshift/console/pull/1035

/hold

### CODE REVIEW

**Comment by ingvagabund** [comment]
https://github.com/openshift/machine-api-operator/pull/167#issuecomment-452684222 needs to be resolved first

**Comment by enxebre** [comment]
Before merging this please make sure this is updated https://github.com/openshift/console/search?q=providerConfig&unscoped_q=providerConfig

**Comment by ingvagabund** [comment]
> Before merging this please make sure this is updated https://github.com/openshift/console/search?q=providerConfig&unscoped_q=providerConfig

https://github.com/openshift/console/pull/1035

**Comment by ingvagabund** [comment]
/hold

devel freeze on Friday, merging only important changes.

**Comment by enxebre** [comment]
Thanks! Please either rebase with only relevant commits and meaningful message or close in favour of https://github.com/openshift/machine-api-operator/pull/170

**Comment by ingvagabund** [comment]
https://github.com/openshift/machine-api-operator/pull/170 is better choice

**Pull request closed without merging**
