### PR TITLE
Bug 1910318: Ensure original conditions aren't mutated during reconcile

### PR DESCRIPTION
**Pull request by JoelSpeed**
If the original conditions are just fetched directly from the machine, this is a reference to a slice. This slice can then be updated by updating the machine conditions. We need to instead have a copy, else the comparison later won't work.

Also, if we mark the condition true then call the actuator update, this can cause issues as the actuator may also patch the machine (eg for providerID). So this needs to come after.

Tested manually on AWS.

### CODE REVIEW

**Review by alexander-demichev — APPROVED** [review]
/approve

**Review by michaelgugino — APPROVED** [review]
/lgtm

**Pull request merged**
