### PR TITLE
Update vendored kubernetes libs to 1.20

### PR DESCRIPTION
**Pull request by kirankt**
This PR updates the vendored k8s.io libraries to v0.20.0 to align with Kubernetes 1.20. In doing so, kubectl's field is also updated to replace the deprecated `DeleteLocalData` with `DeleteEmptyDirData`.

### CODE REVIEW

**Comment by stbenjam** [comment]
Were all the changes we needed handled by https://github.com/openshift/machine-api-operator/pull/705?

**Comment by sadasu** [comment]
> Were all the changes we needed handled by #705?

Yes, this PR can be closed.

**Comment by stbenjam** [comment]
Thanks!

**Pull request closed without merging**
