### PR TITLE
[release-4.6] Bug 1933676: Cherry-pick: Azure disconnected reject publicIP setting

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
Manual cherry-pick of 
- https://github.com/openshift/machine-api-operator/pull/746
- https://github.com/openshift/machine-api-operator/pull/749

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/approve

**Comment by derekwaynecarr** [comment]
(Patch Manager) met criteria, approved

**Pull request merged**
