### PR TITLE
BUG 1824497: Enable error checks to unwrap errors

### PR DESCRIPTION
**Pull request by JoelSpeed**
https://github.com/openshift/cluster-api-provider-aws/pull/309 introduced error wrapping around some of the errors in returned by the actuator. This meant that these checks for errors may no longer work depending on whether the error was wrapped or not.

In particular, any error on launching the instance was being wrapped and as such, the Machine was not going into the failed phase.

This should prevent this sort of thing in the future by updating the checks to unwrap errors before checking them against the given type.

This uses `errors.As` which unwraps until it finds an error of the given type, or returns false if the error is not an error or wrapped error of the given type

### CODE REVIEW

**Comment by enxebre** [comment]
nice
Please can you make sure to reference here the counter part PRs for actuators?
/approve

**Comment by JoelSpeed** [comment]
/hold

I want to verify this before it merges

**Comment by JoelSpeed** [comment]
/hold cancel

I've verified this works to solve the bug in conjunction with https://github.com/openshift/cluster-api-provider-aws/pull/316

**Pull request merged**
