### PR TITLE
Add powervs-machine-controllers to images configmap

### PR DESCRIPTION
**Pull request by mkumatag**
Add the missing image entry for the PowerVS platform

The initial support is pushed via - https://github.com/openshift/machine-api-operator/pull/923

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@mkumatag Can you please confirm/prove that the image has been added to the release payload before we merge this PR?

**Comment by clnperez** [comment]
I can confirm: 
```
> oc adm release info quay.io/openshift-release-dev/ocp-release-nightly@sha256:97a373eacfbcc2ae089cf9241caf8111e25db410cc42706782934a000f958bbf | grep powervs
powervs-machine-controllers                    sha256:9436f53a98f258cbf255a0179076c933212c42bf8db356c90aa5418160e1432e
```

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by mkumatag** [comment]
some of these required tests are failing forever,! not sure how to make them happy :P

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-metal-ipi 
/override ci/prow/e2e-metal-ipi-ovn-dualstack
/override ci/prow/e2e-metal-ipi-virtualmedia 

These jobs are not related to the changes in this PR, I'm content this is safe to override

**Pull request merged**
