### PR TITLE
CCO-321: Add service account name to Azure credentials request

### PR DESCRIPTION
**Pull request by dlom**
xref: [CCO-321](https://issues.redhat.com//browse/CCO-321)

* Enhancement proposal: https://github.com/openshift/enhancements/pull/1301
* Corresponding change for `machine-api-provider-azure`: https://github.com/openshift/machine-api-provider-azure/pull/55

### CODE REVIEW

**Comment by dlom** [comment]
/cc @abutcher 

I can't find any platform specific code (except for vSphere) in here, so I'm not sure what to do beyond adding the service account info to the credentials request.  Please advise

**Comment by dlom** [comment]
Ah, I believe I've found it: https://github.com/openshift/machine-api-provider-azure

**Comment by dlom** [comment]
@lobziik can you approve as well please? I think that's all this needs now

**Comment by JoelSpeed** [comment]
Are we content that all dependencies for this are merged? Looks like the tests are passing so I guess we are good? Anything we should be aware of before we merge?

**Comment by abutcher** [comment]
@JoelSpeed Nothing is using `serviceAccountNames` in the Azure `CredentialsRequests` just yet; this is the first step towards creating the managed identity with tooling.

**Pull request merged**
