### PR TITLE
remove limits for pods and operator

### PR DESCRIPTION
**Pull request by sjenning**
@smarterclayton @derekwaynecarr @frobware 

part of a larger effort to make all control plane components Burstable

### CODE REVIEW

**Comment by smarterclayton** [comment]
is there a reason to remove memory limits (other than these might be too low)?

**Comment by sjenning** [comment]
@smarterclayton so that the pod doesn't OOMKill if it burst above the limit for a short time

**Comment by ingvagabund** [comment]
Integration CI fails since there is no deployment deployed actually.

**Comment by ingvagabund** [comment]
```
[root@ip-172-18-24-250 ec2-user]# sudo kubectl describe pod clusterapi-manager-controllers-695987697-xc4lh -n openshift-cluster-api
Name:           clusterapi-manager-controllers-695987697-xc4lh
Namespace:      openshift-cluster-api
Node:           minikube/172.18.24.250
Start Time:     Tue, 05 Feb 2019 13:35:12 +0000
Labels:         api=clusterapi
                k8s-app=controller
                pod-template-hash=251543253
Annotations:    <none>
Status:         Running
IP:             172.17.0.5
Controlled By:  ReplicaSet/clusterapi-manager-controllers-695987697
Containers:
  controller-manager:
    Container ID:  docker://b7fb4f963790343ab2b4a99d3f661d5c08d9799ad395a81c188d7c88f4148c14
    Image:         docker.io/openshift/origin-aws-machine-controllers:v4.0.0
    Image ID:      docker-pullable://docker.io/openshift/origin-aws-machine-controllers@sha256:af0f08e4b8b53e7b22092a70f6a560e3de3d593a62c9c152f8313c2a56ec5b8e
    Port:          <none>
    Host Port:     <none>
    Command:
      ./manager
    Args:
      --logtostderr=true
      --v=3
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 05 Feb 2019 13:35:38 +0000
      Finished:     Tue, 05 Feb 2019 13:35:38 +0000
    Ready:          False
    Restart Count:  2
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  machine-controller:
    Container ID:  docker://17ba0cb0111975778c9ac72311d9b23b616139950cea5d2a7e566553983bca2d
    Image:         docker.io/openshift/origin-aws-machine-controllers:v4.0.0
    Image ID:      docker-pullable://docker.io/openshift/origin-aws-machine-controllers@sha256:af0f08e4b8b53e7b22092a70f6a560e3de3d593a62c9c152f8313c2a56ec5b8e
    Port:          <none>
    Host Port:     <none>
    Command:
      /machine-controller-manager
    Args:
      --logtostderr=true
      --v=3
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 05 Feb 2019 13:35:39 +0000
      Finished:     Tue, 05 Feb 2019 13:35:39 +0000
    Ready:          False
    Restart Count:  2
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  controller-manager-deprecated:
    Container ID:  docker://528b6ad7c88f4f710b6a2abf8eeb3e3fbfbd53c702147b5e5fdfb6d87c89f815
    Image:         quay.io/coreos/cluster-api-provider-aws:origin-v4.0-2019-01-31-041134
    Image ID:      docker-pullable://quay.io/coreos/cluster-api-provider-aws@sha256:aeae14a410a1280d7b9a8df52d2072ac22c8485fd0eabdf7d17debf34bda38ab
    Port:          <none>
    Host Port:     <none>
    Command:
      ./manager
    Args:
      --logtostderr=true
      --v=3
    State:          Running
      Started:      Tue, 05 Feb 2019 13:35:20 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  machine-controller-deprecated:
    Container ID:  docker://0d9bf555a541046bccf7ba868fc8dd401b4a1ef149c7b45a716fd541d1ce506a
    Image:         quay.io/coreos/cluster-api-provider-aws:origin-v4.0-2019-01-31-041134
    Image ID:      docker-pullable://quay.io/coreos/cluster-api-provider-aws@sha256:aeae14a410a1280d7b9a8df52d2072ac22c8485fd0eabdf7d17debf34bda38ab
    Port:          <none>
    Host Port:     <none>
    Command:
      /machine-controller-manager
    Args:
      --logtostderr=true
      --v=3
    State:          Running
      Started:      Tue, 05 Feb 2019 13:35:20 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  nodelink-controller-deprecated:
    Container ID:  docker://d3b507f8da8a2c7ac8a27d85e7480026979591de225a3744d80647d843cbe36b
    Image:         quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134
    Image ID:      docker-pullable://quay.io/coreos/machine-api-operator@sha256:fa4d7b5b8caa5429e313355f9f1b421e42f03ccb07732c18dd451ccbd01529ec
    Port:          <none>
    Host Port:     <none>
    Command:
      /nodelink-controller
    Args:
      --logtostderr=true
      --v=3
    State:          Running
      Started:      Tue, 05 Feb 2019 13:35:23 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  nodelink-controller:
    Container ID:  docker://f5488e913af1d862da12bc308ac4634c7870927b66b9246b00c36301dbb11fc7
    Image:         machine-api-operator:v0.1.0-157-g8e28084
    Image ID:      docker://sha256:bebf0e656dd2973fbf007da1f920aa3e12a08677b261a46f104dbe9513bb2ac9
    Port:          <none>
    Host Port:     <none>
    Command:
      /nodelink-controller
    Args:
      --logtostderr=true
      --v=3
    State:          Running
      Started:      Tue, 05 Feb 2019 13:35:23 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  machine-healthcheck-deprecated:
    Container ID:  docker://3015e21e0b7d174f99e35f928c394629e382ff798a9c224e58127d377fe7cf05
    Image:         quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134
    Image ID:      docker-pullable://quay.io/coreos/machine-api-operator@sha256:fa4d7b5b8caa5429e313355f9f1b421e42f03ccb07732c18dd451ccbd01529ec
    Port:          <none>
    Host Port:     <none>
    Command:
      /machine-healthcheck
    Args:
      --logtostderr=true
      --v=3
    State:          Running
      Started:      Tue, 05 Feb 2019 13:35:23 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
  machine-healthcheck:
    Container ID:  docker://68627ea01aa8a2336419a4a275e9e962e2303bb3c3c66702604f8e5c104fcc66
    Image:         machine-api-operator:v0.1.0-157-g8e28084
    Image ID:      docker://sha256:bebf0e656dd2973fbf007da1f920aa3e12a08677b261a46f104dbe9513bb2ac9
    Port:          <none>
    Host Port:     <none>
    Command:
      /machine-healthcheck
    Args:
      --logtostderr=true
      --v=3
    State:          Running
      Started:      Tue, 05 Feb 2019 13:35:24 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8wnnl (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-8wnnl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-8wnnl
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  node-role.kubernetes.io/master=
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.alpha.kubernetes.io/notReady:NoExecute
                 node.alpha.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason                 Age   From               Message
  ----    ------                 ----  ----               -------
  Normal  Scheduled              32s   default-scheduler  Successfully assigned clusterapi-manager-controllers-695987697-xc4lh to minikube
  Normal  SuccessfulMountVolume  32s   kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-8wnnl"
  Normal  Pulling                32s   kubelet, minikube  pulling image "docker.io/openshift/origin-aws-machine-controllers:v4.0.0"
  Normal  Pulled                 28s   kubelet, minikube  Successfully pulled image "docker.io/openshift/origin-aws-machine-controllers:v4.0.0"
  Normal  Created                28s   kubelet, minikube  Created container
  Normal  Started                28s   kubelet, minikube  Started container
  Normal  Pulled                 28s   kubelet, minikube  Container image "docker.io/openshift/origin-aws-machine-controllers:v4.0.0" already present on machine
  Normal  Created                28s   kubelet, minikube  Created container
  Normal  Started                28s   kubelet, minikube  Started container
  Normal  Pulling                27s   kubelet, minikube  pulling image "quay.io/coreos/cluster-api-provider-aws:origin-v4.0-2019-01-31-041134"
  Normal  Pulling                24s   kubelet, minikube  pulling image "quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134"
  Normal  Created                24s   kubelet, minikube  Created container
  Normal  Started                24s   kubelet, minikube  Started container
  Normal  Pulled                 24s   kubelet, minikube  Successfully pulled image "quay.io/coreos/cluster-api-provider-aws:origin-v4.0-2019-01-31-041134"
  Normal  Created                24s   kubelet, minikube  Created container
  Normal  Started                24s   kubelet, minikube  Started container
  Normal  Pulled                 24s   kubelet, minikube  Container image "quay.io/coreos/cluster-api-provider-aws:origin-v4.0-2019-01-31-041134" already present on machine
  Normal  Pulled                 21s   kubelet, minikube  Successfully pulled image "quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134"
  Normal  Created                21s   kubelet, minikube  Created container
  Normal  Started                21s   kubelet, minikube  Started container
  Normal  Pulled                 21s   kubelet, minikube  Container image "machine-api-operator:v0.1.0-157-g8e28084" already present on machine
  Normal  Created                21s   kubelet, minikube  Created container
  Normal  Started                21s   kubelet, minikube  Started container
  Normal  Pulled                 21s   kubelet, minikube  Container image "quay.io/coreos/machine-api-operator:origin-v4.0-2019-01-31-041134" already present on machine
  Normal  Created                21s   kubelet, minikube  Created container
  Normal  Started                20s   kubelet, minikube  Started container
```

```
[root@ip-172-18-24-250 ec2-user]# sudo kubectl logs clusterapi-manager-controllers-695987697-xc4lh -n openshift-cluster-api -c machine-controller
I0205 13:36:59.096576       1 main.go:57] Registering Components.
F0205 13:36:59.097168       1 main.go:70] no matches for kind "Machine" in version "machine.openshift.io/v1beta1"
[root@ip-172-18-24-250 ec2-user]# sudo kubectl logs clusterapi-manager-controllers-695987697-xc4lh -n openshift-cluster-api -c controller-manager
2019/02/05 13:36:58 Registering Components.
2019/02/05 13:36:58 no matches for kind "MachineDeployment" in version "machine.openshift.io/v1beta1"
```

**Comment by ingvagabund** [comment]
```
[root@ip-172-18-24-250 ec2-user]# sudo kubectl logs clusterapi-manager-controllers-695987697-xc4lh -n openshift-cluster-api -c machine-controller
I0205 13:36:59.096576       1 main.go:57] Registering Components.
F0205 13:36:59.097168       1 main.go:70] no matches for kind "Machine" in version "machine.openshift.io/v1beta1"
[root@ip-172-18-24-250 ec2-user]# sudo kubectl logs clusterapi-manager-controllers-695987697-xc4lh -n openshift-cluster-api -c controller-manager
2019/02/05 13:36:58 Registering Components.
2019/02/05 13:36:58 no matches for kind "MachineDeployment" in version "machine.openshift.io/v1beta1"
```

**Comment by ingvagabund** [comment]
```
# kubectl get crd 
NAME                                              AGE
clusteroperators.config.openshift.io              6m
clusters.cluster.k8s.io                           6m
machinedeployments.cluster.k8s.io                 6m
machinehealthchecks.healthchecking.openshift.io   6m
machines.cluster.k8s.io                           6m
machinesets.cluster.k8s.io                        6m
```

the new crds are not deployed yet, checking the CI

**Comment by ingvagabund** [comment]
For some reason the machine controller container runs but then exists without any error message.

**Comment by enxebre** [comment]
Thanks @sjenning! closed by https://github.com/openshift/machine-api-operator/commit/c14069bfcdc520624adfdc86d048634584f01769#diff-71ce95449fb096da82e00900d6fd2531 and https://github.com/openshift/machine-api-operator/pull/228/files

**Pull request closed without merging**
