### PR TITLE
Add service account names to gcp credentials request manifest

### PR DESCRIPTION
**Pull request by akhil-rane**
For enabling short-lived credentials in gcp cluster using workload
identity (similar to AWS STS), we need ccoctl tool to know the 
kubernetes service account names from the credentials request 
manifest so that it can create gcp service accounts that can be 
impersonated only by specific kubernetes service accounts.

ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
x-ref: https://issues.redhat.com/browse/CCO-114

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Is there an enhancement or any documentation for this project? Is this something the CCO team is targeting for 4.9?

**Comment by akhil-rane** [comment]
> Is there an enhancement or any documentation for this project? Is this something the CCO team is targeting for 4.9?

We are still investigating if it is feasible with Openshift and if yes what changes will be required. There is no documentation or enhancement yet. Hopefully we will have something soon once we figure out all the pieces.

**Comment by akhil-rane** [comment]
> Is there an enhancement or any documentation for this project? Is this something the CCO team is targeting for 4.9?

**Comment by akhil-rane** [comment]
> Is there an enhancement or any documentation for this project? Is this something the CCO team is targeting for 4.9?

@JoelSpeed here is the jira epic for this PR https://issues.redhat.com/browse/CCO-114

**Comment by akhil-rane** [comment]
@JoelSpeed updated github.com/openshift/cluster-api-provider-gcp to point to latest commit with workload identity changes. PTAL.

**Comment by akhil-rane** [comment]
@JoelSpeed this has passed all required and gcp tests. Need lgtm label to merge.

**Pull request merged**
