### PR TITLE
Update OpenShift API to include placement groups

### PR DESCRIPTION
**Pull request by JoelSpeed**
This PR updates the openshift/api repo dependency and installs the new AWSPlacementGroup CRD within clusters

This will only be able to merge once openshift/api#1091 has been merged

### CODE REVIEW

**Review by damdo — COMMENTED** [review]
As you mentioned it will need the canonical api import, but other than that it, LGTM

**Comment by damdo** [comment]
I see the api change to the canonical openshift/api has merged and is now referenced.
/lgtm

**Comment by JoelSpeed** [comment]
This PR is blocked until https://github.com/openshift/cluster-machine-approver/pull/156 merges
/hold

**Pull request merged**
