### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by liangxia**
Follow up of https://github.com/openshift/machine-api-operator/pull/196

### CODE REVIEW

**Comment by ingvagabund** [comment]
Hi @liangxia, thank you for the PR.

We are removing anything under `test` directory (see [1]). Though, all the crds under `test/integration` are just symlinks to those under `install` directory. Can you replace all `test/integration` paths with `install`? Otherwise, lgtm.

[1] https://github.com/openshift/machine-api-operator/pull/240

**Comment by liangxia** [comment]
@ingvagabund  Updated. Could you help check ?

**Pull request merged**
