### PR TITLE
Add resource limit to pods

### PR DESCRIPTION
**Pull request by alexander-demichev**
Add resource limit to pods. This should prevent our pods from consuming too many resources.

### CODE REVIEW

**Review by JoelSpeed — APPROVED** [review]
/approve

Seems reasonable to me

**Comment by smarterclayton** [comment]
this is in direct violation of https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#resources-and-limits

please read the section.  cpu limits are never allowed in payload, and memory limits are only allowed after review

**Comment by smarterclayton** [comment]
to help you understand what the exceptions are i’ll add a section to the doc - generally it’s “if your workload has a fixed usage no matter the size of cluster, size of workload, or size of node you may set a memory limit, but only if you can demonstrate that a customer in production cannot hit that limit”.  There’s more nuance than that, but that roughly describes what is allowed.

after we document that, we’ll decide whether to add an exception to https://github.com/openshift/origin/pull/25959 (which is what clarifies this behavior)

**Comment by JoelSpeed** [comment]
@alexander-demichev based on @smarterclayton's comments above, I think we should revert this all for now and then have a discussion explicitly about the spot termination handler and adding a limit to that.

AFAIK that is the only one of our components that should truly be scale invariant no matter the size of the workload

**Pull request merged**
